apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ printf "%s-%s" .Values.org.name .Values.team.name | squote}}
spec:
  description: {{ printf "Team: %s Organization: %s" .Values.team.name .Values.org.name | squote }}
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: {{ printf "%s-%s-*" .Values.org.name .Values.team.name | squote }}
      server: https://kubernetes.default.svc
  sourceRepos:
    - '*'
  sourceNamespaces:
    - {{ printf "%s-argocd" .Values.org.name | squote }}
