apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ printf "%s-%s" .Values.org.name .Values.team.name }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: {{ printf "%s-%s-*" .Values.org.name .Values.team.name | squote }}
      server: '*'
  sourceRepos:
    - '*'
