apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/trevorbox/gitops-example-iac-argocd-apps.git'
    targetRevision: HEAD
    path: helm/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
