apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: team-apps-{{ .Values.cluster.name }}
spec:
  goTemplate: true
  syncPolicy:
    preserveResourcesOnDeletion: {{ .Values.preserveResourcesOnDeletion }}
  generators:
    - git:
        repoURL: 'https://github.com/trevorbox/gitops-example-iac-argocd-apps.git'
        revision: HEAD
        files:
          - path: {{ printf "clusters/%s/orgs/*/teams/*/contexts/*/apps/*.yaml" .Values.cluster.name }}
  template:
    metadata:
      name: >-
        {{ printf "{{index .path.segments 3}}-{{index .path.segments 5}}-{{index .path.segments 7}}-{{index (splitList "." .path.filenameNormalized) 0}}" }}
    spec:
      project: >-
        {{ printf "{{index .path.segments 3}}-{{index .path.segments 5}}" }}
      source:
        path: >-
          {{ printf "{{.source.path}}" }}
        repoURL: >-
          {{ printf "{{.source.repoURL}}" }}
        targetRevision: >-
          {{ printf "{{.source.targetRevision}}" }}
        helm:
          valueFiles:
            - >- 
              {{ printf "{{.source.helm.valuesFile}}" }}
      destination:
        server: https://kubernetes.default.svc
        namespace: >-
          {{ printf "{{index .path.segments 3}}-{{index .path.segments 5}}-{{index .path.segments 7}}" }}
      syncPolicy:
        automated: 
          prune: true
          selfHeal: true
