apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rootapp-{{ .Values.cluster.name }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/trevorbox/gitops-example-iac-argocd-apps.git'
    targetRevision: test-label-key
    path: helm/applications
    helm:
      values: |
        cluster:
          name: {{ .Values.cluster.name }}
        org:
          name: {{ .Values.org.name }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
