apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rootapp-{{ .Values.cluster.name }}
spec:
  project: default
  source:
    repoURL: 'https://github.com/trevorbox/gitops-example-iac-argocd-apps.git'
    targetRevision: HEAD
    path: helm/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
